projectVersion=1.0.0-SNAPSHOT

title=Micronaut AOT test module
projectDesc=Build time optimizations for Micronaut
projectUrl=https://micronaut.io
githubSlug=micronaut-projects/micronaut-aot-test-module
developers=Graeme Rocher

# Micronaut core branch for BOM pull requests
githubCoreBranch=4.9.x

bomProperty=micronautAotVersion

org.gradle.caching=true
org.gradle.parallel=true
