plugins {
    id 'io.micronaut.build.internal.java-base'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation libs.junit6.api
    testRuntimeOnly libs.junit6.engine
    testRuntimeOnly libs.junit6.launcher
}

tasks.named('test') {
    dependsOn rootProject.tasks.named('docs')
    systemProperty 'docs.guide', rootProject.layout.buildDirectory.file('docs/guide/index.html').get().asFile.absolutePath
    systemProperty 'docs.configReference', rootProject.layout.buildDirectory.file('docs/guide/configurationreference.html').get().asFile.absolutePath
    systemProperty 'docs.apiIndex', rootProject.layout.buildDirectory.file('docs/api/index.html').get().asFile.absolutePath
}
