projectVersion=1.0.0-SNAPSHOT
projectGroup=io.micronaut.dummy

title=Micronaut lambda desugaring test module
projectDesc=Lambda desugaring trial
projectUrl=https://micronaut.io
githubSlug=micronaut-projects/micronaut-desugar-test-module
developers=Graeme Rocher

# Micronaut core branch for BOM pull requests
githubCoreBranch=5.3.x
