package io.micronaut.docs

import groovy.transform.CompileStatic

@CompileStatic
class MicronautDocsResources {
    static final String LOGO = 'micronaut-logo-white.svg'

    static final List<String> IMG = [
            LOGO
    ]
    static final List<String> JS = [
        'guide.js',
        'highlight.pack.js',
        'multi-language-sample.js',
    ]
    static final List<String> STYLE = [
        'layout.html',
        'page.html',
        'section.html',
    ]
    static final List<String> CSS = [
            'custom.css',
            'multi-language-sample.css',
            'highlight/agate.css',
            'highlight/androidstudio.css',
            'highlight/arduino-light.css',
            'highlight/arta.css',
            'highlight/ascetic.css',
            'highlight/atelier-cave-dark.css',
            'highlight/atelier-cave-light.css',
            'highlight/atelier-dune-dark.css',
            'highlight/atelier-dune-light.css',
            'highlight/atelier-estuary-dark.css',
            'highlight/atelier-estuary-light.css',
            'highlight/atelier-forest-dark.css',
            'highlight/atelier-forest-light.css',
            'highlight/atelier-heath-dark.css',
            'highlight/atelier-heath-light.css',
            'highlight/atelier-lakeside-dark.css',
            'highlight/atelier-lakeside-light.css',
            'highlight/atelier-plateau-dark.css',
            'highlight/atelier-plateau-light.css',
            'highlight/atelier-savanna-dark.css',
            'highlight/atelier-savanna-light.css',
            'highlight/atelier-seaside-dark.css',
            'highlight/atelier-seaside-light.css',
            'highlight/atelier-sulphurpool-dark.css',
            'highlight/atelier-sulphurpool-light.css',
            'highlight/atom-one-dark.css',
            'highlight/atom-one-light.css',
            'highlight/brown-paper.css',
            'highlight/brown-papersq.png',
            'highlight/codepen-embed.css',
            'highlight/color-brewer.css',
            'highlight/darcula.css',
            'highlight/dark.css',
            'highlight/darkula.css',
            'highlight/default.css',
            'highlight/docco.css',
            'highlight/dracula.css',
            'highlight/far.css',
            'highlight/foundation.css',
            'highlight/github-gist.css',
            'highlight/github.css',
            'highlight/googlecode.css',
            'highlight/grayscale.css',
            'highlight/gruvbox-dark.css',
            'highlight/gruvbox-light.css',
            'highlight/hopscotch.css',
            'highlight/hybrid.css',
            'highlight/idea.css',
            'highlight/ir-black.css',
            'highlight/kimbie.dark.css',
            'highlight/kimbie.light.css',
            'highlight/magula.css',
            'highlight/mono-blue.css',
            'highlight/monokai-sublime.css',
            'highlight/monokai.css',
            'highlight/obsidian.css',
            'highlight/ocean.css',
            'highlight/paraiso-dark.css',
            'highlight/paraiso-light.css',
            'highlight/pojoaque.css',
            'highlight/pojoaque.jpg',
            'highlight/purebasic.css',
            'highlight/qtcreator_dark.css',
            'highlight/qtcreator_light.css',
            'highlight/railscasts.css',
            'highlight/rainbow.css',
            'highlight/routeros.css',
            'highlight/school-book.css',
            'highlight/school-book.png',
            'highlight/solarized-dark.css',
            'highlight/solarized-light.css',
            'highlight/sunburst.css',
            'highlight/tomorrow-night-blue.css',
            'highlight/tomorrow-night-bright.css',
            'highlight/tomorrow-night-eighties.css',
            'highlight/tomorrow-night.css',
            'highlight/tomorrow.css',
            'highlight/vs.css',
            'highlight/vs2015.css',
            'highlight/xcode.css',
            'highlight/xt256.css',
            'highlight/zenburn.css']
}
