name: Update Dependencies
on:
  schedule:
    - cron: '0 4 * * MON-FRI'
jobs:
  dependency-updates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2.1.4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Check Dependencies
        run: ./gradlew useLatestVersions
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.8.2
        with:
          token: ${{ secrets.GH_TOKEN }}
          committer: micronaut-build <${{ secrets.MICRONAUT_BUILD_EMAIL }}>
          author: micronaut-build <${{ secrets.MICRONAUT_BUILD_EMAIL }}>
          commit-message: Update dependencies
          title: 'Dependency upgrades'
          body: Upgrades dependencies to their latest versions
          labels: "type: dependency-upgrade"
          base: master
          branch: dependency-updates