name: Changelog
on:
  issues:
    types: [closed,reopened]
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
jobs:
  release_notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Export Gradle Properties
        uses: micronaut-projects/github-actions/export-gradle-properties@master
      - uses: micronaut-projects/github-actions/release-notes@master
        id: release_notes
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: ncipollo/release-action@v1.9.0
        if: steps.release_notes.outputs.generated_changelog == 'true'
        with:
          allowUpdates: true
          commit: master
          draft: true
          name: ${{ env.title }} ${{ steps.release_notes.outputs.next_version }}
          tag: v${{ steps.release_notes.outputs.next_version }}
          bodyFile: CHANGELOG.md
          token: ${{ secrets.GH_TOKEN }}
